const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: false,
      unique: true,
      //index: true,
    },
    password: {
      type: String,
      required: false, //because it is autogenerated
    },
    empID: {
      type: String,
      required: false,
      unique: true,
      //index: true,
    },
    designation: {
      type: String,
      required: false,
      enum:["Software Engineer","Team Lead","Manager","HR","UI/UX Designer","Data Analyst","CTO","CEO","Founder"]
    },
    phoneNo: {
      type: String,
      required: true,
      index: true,
    },
    department: {
      type: String,
      required: false,
    },
    team: {
      type: String,
      required: false,
    },
    role: {
      type: String,
      required: false,
      enum: ["User", "Admin", "Super-Admin", "Manager", "HR", "Team-Lead"],
      default: "User",
    },
    joiningDate: {
      type: Date,
      required: false,
    },
    address: {
      type: String,
      required: false,
    },
    nearestMetroStation: {
      type: String,
      required: false,
    },
    transportType: {
      type: String,
      required: false,
    },
    token: {
      type: String,
      required: false,
    },
    isFirstLogin: {
      type: Boolean,
      default: true,
    },
    isVerified:{
      type: Boolean,
      default: false
    }
  },
  {
    timestamps: true,
  }
);

const User = mongoose.model("User", userSchema, "users");

module.exports = { User };
